/**
 * HSSF monorepo production build (PR-09)
 * - JS: esbuild → IIFE debug + IIFE min + ESM + ESM min
 * - CSS: ordered concat + esbuild minify for hssf.min.css
 * - Vendor: atom-one-dark.css copy
 * - Writes dist/build-meta.json (sizes)
 */

import * as esbuild from "esbuild";
import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const pkgDir = path.join(root, "packages", "hssf");
const srcJs = path.join(pkgDir, "src", "js", "index.js");
const srcBrowser = path.join(pkgDir, "src", "js", "browser.js");
const cssDir = path.join(pkgDir, "src", "css");
const distDir = path.join(pkgDir, "dist");

const requireFromHssf = createRequire(path.join(pkgDir, "package.json"));

const CSS_ORDER = [
  "tokens.css",
  "base.css",
  "chrome.css",
  "fragments.css",
  "components/layout.css",
  "components/content.css",
  "components/teaching.css",
  "components/visual.css",
  "components/media.css",
  "components/flow.css",
  "components/effects.css",
  "components/term.css",
  "print.css",
];

const IIFE_API =
  "{init:HSSF.init,version:HSSF.version,highlight:HSSF.highlight,hljs:HSSF.hljs,fitStage:HSSF.fitStage,computeScale:HSSF.computeScale,parseHash:HSSF.parseHash,formatHash:HSSF.formatHash,toggleFullscreen:HSSF.toggleFullscreen}";

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function resolveAtomOneDarkCss() {
  try {
    return requireFromHssf.resolve("highlight.js/styles/atom-one-dark.css");
  } catch {
    const candidates = [
      path.join(root, "node_modules", "highlight.js", "styles", "atom-one-dark.css"),
      path.join(pkgDir, "node_modules", "highlight.js", "styles", "atom-one-dark.css"),
    ];
    for (const c of candidates) {
      if (fs.existsSync(c)) return c;
    }
    throw new Error(
      "[build] Cannot resolve highlight.js/styles/atom-one-dark.css — run pnpm install",
    );
  }
}

function readCssOrdered() {
  const parts = [];
  for (const rel of CSS_ORDER) {
    const full = path.join(cssDir, rel);
    if (fs.existsSync(full)) {
      parts.push(`/* === ${rel} === */\n${fs.readFileSync(full, "utf8")}`);
    }
  }

  const oneDarkPath = resolveAtomOneDarkCss();
  const oneDark = fs.readFileSync(oneDarkPath, "utf8");
  parts.push(
    `/* === vendor: highlight.js atom-one-dark.css === */\n${oneDark}`,
  );
  fs.copyFileSync(oneDarkPath, path.join(distDir, "atom-one-dark.css"));

  return parts.join("\n\n");
}

async function buildJs() {
  const target = ["es2020"];
  const iifeFooter = `if(typeof HSSF!=="undefined"&&HSSF.init&&typeof window!=="undefined"){window.HSSF=${IIFE_API};}`;
  const iifeFooterMin = `typeof HSSF<"u"&&HSSF.init&&typeof window<"u"&&(window.HSSF=${IIFE_API});`;

  await esbuild.build({
    entryPoints: [srcBrowser],
    bundle: true,
    target,
    logLevel: "info",
    outfile: path.join(distDir, "hssf.js"),
    format: "iife",
    globalName: "HSSF",
    minify: false,
    footer: { js: iifeFooter },
  });

  await esbuild.build({
    entryPoints: [srcBrowser],
    bundle: true,
    target,
    logLevel: "info",
    outfile: path.join(distDir, "hssf.min.js"),
    format: "iife",
    globalName: "HSSF",
    minify: true,
    legalComments: "none",
    footer: { js: iifeFooterMin },
  });

  await esbuild.build({
    entryPoints: [srcJs],
    bundle: true,
    target,
    logLevel: "info",
    outfile: path.join(distDir, "hssf.esm.js"),
    format: "esm",
    minify: false,
  });

  await esbuild.build({
    entryPoints: [srcJs],
    bundle: true,
    target,
    logLevel: "info",
    outfile: path.join(distDir, "hssf.esm.min.js"),
    format: "esm",
    minify: true,
    legalComments: "none",
  });
}

async function buildCss() {
  const css = readCssOrdered();
  const banner =
    "/* hssf CSS — generated by scripts/build.mjs (includes highlight.js atom-one-dark) */\n";
  fs.writeFileSync(path.join(distDir, "hssf.css"), banner + css, "utf8");

  const minResult = await esbuild.transform(css, {
    loader: "css",
    minify: true,
    target: ["chrome80", "firefox78", "safari13"],
  });
  fs.writeFileSync(
    path.join(distDir, "hssf.min.css"),
    `/* hssf min + atom-one-dark */${minResult.code}`,
    "utf8",
  );
}

function writeMeta() {
  const files = fs.readdirSync(distDir).filter((f) => !f.endsWith(".json"));
  const assets = {};
  for (const f of files) {
    const buf = fs.readFileSync(path.join(distDir, f));
    assets[f] = {
      bytes: buf.length,
      gzip: zlib.gzipSync(buf, { level: 9 }).length,
    };
  }
  const meta = {
    builtAt: new Date().toISOString(),
    package: "hssf",
    version: JSON.parse(
      fs.readFileSync(path.join(pkgDir, "package.json"), "utf8"),
    ).version,
    assets,
    note: "JS includes highlight.js/lib/common; CSS includes atom-one-dark",
  };
  fs.writeFileSync(
    path.join(distDir, "build-meta.json"),
    JSON.stringify(meta, null, 2) + "\n",
    "utf8",
  );
  return meta;
}

async function main() {
  ensureDir(distDir);
  if (!fs.existsSync(srcJs)) {
    console.error(`[build] missing entry: ${srcJs}`);
    process.exit(1);
  }
  await buildJs();
  await buildCss();
  const meta = writeMeta();
  console.log(`[build] wrote dist → ${distDir}`);
  for (const [f, s] of Object.entries(meta.assets)) {
    console.log(`  ${f}  (${s.bytes} bytes, gzip ${s.gzip})`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
